/*
	3dto3d engine by tb-software.com (support@tb-software.com)
	Created by POV Export Plugin 1.2 at Thu Jul 07 04:07:37 2011

	Material file:
*/

#declare full_filter_pigment = pigment // full_filter_pigment
{
	transmit 1.0
}

#declare full_filter_normal = normal // full_filter_normal
{
	bumps, 0.000000
}

#declare T_def_mat = 
texture // def_mat
{
pigment
{
	color rgbt <1.000000, 1.000000, 1.000000, 0.000000>
}

}

